#!/bin/bash

# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# TODO(wiley) Remove this on July 20 2015.
echo 'The logic in this script has moved.'
echo 'Please run `/mnt/host/source/src/scripts/update_chroot`'
exit 1
