#!/bin/bash

# Copyright 2018 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
if [[ -d "${BUILD_DIR}/test_demo_resources" ]]; then
  mv "${BUILD_DIR}/test_demo_resources" \
      "${STATEFUL_DIR}/unencrypted/demo_mode_resources"
fi
